docker-compose.yml
frontend/.gitignore
frontend/README.md
frontend/eslint.config.js
frontend/index.html
frontend/package-lock.json
frontend/package.json
frontend/public/favicon.svg
frontend/public/icons.svg
frontend/src/App.css
frontend/src/App.jsx
frontend/src/assets/hero.png
frontend/src/assets/react.svg
frontend/src/assets/vite.svg
frontend/src/components/Navbar.jsx
frontend/src/components/PredictionForm.jsx
frontend/src/components/ResultCard.jsx
frontend/src/components/RevenueChart.jsx
frontend/src/pages/AboutPage.jsx
frontend/src/pages/Dashboard.jsx
frontend/src/pages/Home.jsx
frontend/src/pages/Homepage.jsx
frontend/src/pages/InsightPage.jsx
frontend/src/pages/PredictRevenue.jsx
frontend/src/pages/PredictionPage.jsx
frontend/src/services/api.js
frontend/src/vercel.json
frontend/vite.config.js
